//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legato.ServiceDAL.Middleware.LegatoMiddleware {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Legato.Middleware.LegatoMiddleware.ILegatoMiddleware")]
    public interface ILegatoMiddleware {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetAllGuitars", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetAllGuitarsResponse")]
        Legato.MiddlewareContracts.DataContracts.GuitarDataModel[] GetAllGuitars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetAllGuitars", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetAllGuitarsResponse")]
        System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.GuitarDataModel[]> GetAllGuitarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetGuitarsByPrice", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetGuitarsByPriceResponse")]
        Legato.MiddlewareContracts.DataContracts.GuitarDataModel[] GetGuitarsByPrice(short from, short to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetGuitarsByPrice", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetGuitarsByPriceResponse")]
        System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.GuitarDataModel[]> GetGuitarsByPriceAsync(short from, short to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetAcousticClassicalGuitarsByPrice", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetAcousticClassicalGuitarsByPriceResponse")]
        Legato.MiddlewareContracts.DataContracts.AcousticClassicalGuitarDataModel[] GetAcousticClassicalGuitarsByPrice(short from, short to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetAcousticClassicalGuitarsByPrice", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetAcousticClassicalGuitarsByPriceResponse")]
        System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.AcousticClassicalGuitarDataModel[]> GetAcousticClassicalGuitarsByPriceAsync(short from, short to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetAcousticWesternGuitarsByPrice", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetAcousticWesternGuitarsByPriceResponse")]
        Legato.MiddlewareContracts.DataContracts.AcousticWesternGuitarDataModel[] GetAcousticWesternGuitarsByPrice(short from, short to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetAcousticWesternGuitarsByPrice", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetAcousticWesternGuitarsByPriceResponse")]
        System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.AcousticWesternGuitarDataModel[]> GetAcousticWesternGuitarsByPriceAsync(short from, short to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetBassGuitarsByPrice", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetBassGuitarsByPriceResponse")]
        Legato.MiddlewareContracts.DataContracts.BassGuitarDataModel[] GetBassGuitarsByPrice(short from, short to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetBassGuitarsByPrice", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetBassGuitarsByPriceResponse")]
        System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.BassGuitarDataModel[]> GetBassGuitarsByPriceAsync(short from, short to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetElectroGuitarsByPrice", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetElectroGuitarsByPriceResponse")]
        Legato.MiddlewareContracts.DataContracts.ElectroGuitarDataModel[] GetElectroGuitarsByPrice(short from, short to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetElectroGuitarsByPrice", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetElectroGuitarsByPriceResponse")]
        System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.ElectroGuitarDataModel[]> GetElectroGuitarsByPriceAsync(short from, short to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetAllAcousticClassicalGuitars", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetAllAcousticClassicalGuitarsResponse")]
        Legato.MiddlewareContracts.DataContracts.AcousticClassicalGuitarDataModel[] GetAllAcousticClassicalGuitars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetAllAcousticClassicalGuitars", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetAllAcousticClassicalGuitarsResponse")]
        System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.AcousticClassicalGuitarDataModel[]> GetAllAcousticClassicalGuitarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetAllAcousticWesternGuitars", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetAllAcousticWesternGuitarsResponse")]
        Legato.MiddlewareContracts.DataContracts.AcousticWesternGuitarDataModel[] GetAllAcousticWesternGuitars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetAllAcousticWesternGuitars", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetAllAcousticWesternGuitarsResponse")]
        System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.AcousticWesternGuitarDataModel[]> GetAllAcousticWesternGuitarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetAllElectroGuitars", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetAllElectroGuitarsResponse")]
        Legato.MiddlewareContracts.DataContracts.ElectroGuitarDataModel[] GetAllElectroGuitars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetAllElectroGuitars", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetAllElectroGuitarsResponse")]
        System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.ElectroGuitarDataModel[]> GetAllElectroGuitarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetAllBassGuitars", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetAllBassGuitarsResponse")]
        Legato.MiddlewareContracts.DataContracts.BassGuitarDataModel[] GetAllBassGuitars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetAllBassGuitars", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetAllBassGuitarsResponse")]
        System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.BassGuitarDataModel[]> GetAllBassGuitarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetGuitarsByVendor", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetGuitarsByVendorResponse")]
        Legato.MiddlewareContracts.DataContracts.GuitarDataModel[] GetGuitarsByVendor(string vendor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetGuitarsByVendor", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetGuitarsByVendorResponse")]
        System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.GuitarDataModel[]> GetGuitarsByVendorAsync(string vendor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetAcousticClassicalGuitarsByVendor", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetAcousticClassicalGuitarsByVendorResponse")]
        Legato.MiddlewareContracts.DataContracts.AcousticClassicalGuitarDataModel[] GetAcousticClassicalGuitarsByVendor(string vendor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetAcousticClassicalGuitarsByVendor", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetAcousticClassicalGuitarsByVendorResponse")]
        System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.AcousticClassicalGuitarDataModel[]> GetAcousticClassicalGuitarsByVendorAsync(string vendor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetAcousticWesternGuitarsByVendor", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetAcousticWesternGuitarsByVendorResponse")]
        Legato.MiddlewareContracts.DataContracts.AcousticWesternGuitarDataModel[] GetAcousticWesternGuitarsByVendor(string vendor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetAcousticWesternGuitarsByVendor", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetAcousticWesternGuitarsByVendorResponse")]
        System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.AcousticWesternGuitarDataModel[]> GetAcousticWesternGuitarsByVendorAsync(string vendor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetElectroGuitarsByVendor", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetElectroGuitarsByVendorResponse")]
        Legato.MiddlewareContracts.DataContracts.ElectroGuitarDataModel[] GetElectroGuitarsByVendor(string vendor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetElectroGuitarsByVendor", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetElectroGuitarsByVendorResponse")]
        System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.ElectroGuitarDataModel[]> GetElectroGuitarsByVendorAsync(string vendor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetBassGuitarsByVendor", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetBassGuitarsByVendorResponse")]
        Legato.MiddlewareContracts.DataContracts.BassGuitarDataModel[] GetBassGuitarsByVendor(string vendor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILegatoMiddleware/GetBassGuitarsByVendor", ReplyAction="http://tempuri.org/ILegatoMiddleware/GetBassGuitarsByVendorResponse")]
        System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.BassGuitarDataModel[]> GetBassGuitarsByVendorAsync(string vendor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILegatoMiddlewareChannel : ILegatoMiddleware, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LegatoMiddlewareClient : System.ServiceModel.ClientBase<ILegatoMiddleware>, ILegatoMiddleware
    {
        
        public LegatoMiddlewareClient() {
        }
        
        public LegatoMiddlewareClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LegatoMiddlewareClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LegatoMiddlewareClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LegatoMiddlewareClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Legato.MiddlewareContracts.DataContracts.GuitarDataModel[] GetAllGuitars() {
            return base.Channel.GetAllGuitars();
        }
        
        public System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.GuitarDataModel[]> GetAllGuitarsAsync() {
            return base.Channel.GetAllGuitarsAsync();
        }
        
        public Legato.MiddlewareContracts.DataContracts.GuitarDataModel[] GetGuitarsByPrice(short from, short to) {
            return base.Channel.GetGuitarsByPrice(from, to);
        }
        
        public System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.GuitarDataModel[]> GetGuitarsByPriceAsync(short from, short to) {
            return base.Channel.GetGuitarsByPriceAsync(from, to);
        }
        
        public Legato.MiddlewareContracts.DataContracts.AcousticClassicalGuitarDataModel[] GetAcousticClassicalGuitarsByPrice(short from, short to) {
            return base.Channel.GetAcousticClassicalGuitarsByPrice(from, to);
        }
        
        public System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.AcousticClassicalGuitarDataModel[]> GetAcousticClassicalGuitarsByPriceAsync(short from, short to) {
            return base.Channel.GetAcousticClassicalGuitarsByPriceAsync(from, to);
        }
        
        public Legato.MiddlewareContracts.DataContracts.AcousticWesternGuitarDataModel[] GetAcousticWesternGuitarsByPrice(short from, short to) {
            return base.Channel.GetAcousticWesternGuitarsByPrice(from, to);
        }
        
        public System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.AcousticWesternGuitarDataModel[]> GetAcousticWesternGuitarsByPriceAsync(short from, short to) {
            return base.Channel.GetAcousticWesternGuitarsByPriceAsync(from, to);
        }
        
        public Legato.MiddlewareContracts.DataContracts.BassGuitarDataModel[] GetBassGuitarsByPrice(short from, short to) {
            return base.Channel.GetBassGuitarsByPrice(from, to);
        }
        
        public System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.BassGuitarDataModel[]> GetBassGuitarsByPriceAsync(short from, short to) {
            return base.Channel.GetBassGuitarsByPriceAsync(from, to);
        }
        
        public Legato.MiddlewareContracts.DataContracts.ElectroGuitarDataModel[] GetElectroGuitarsByPrice(short from, short to) {
            return base.Channel.GetElectroGuitarsByPrice(from, to);
        }
        
        public System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.ElectroGuitarDataModel[]> GetElectroGuitarsByPriceAsync(short from, short to) {
            return base.Channel.GetElectroGuitarsByPriceAsync(from, to);
        }
        
        public Legato.MiddlewareContracts.DataContracts.AcousticClassicalGuitarDataModel[] GetAllAcousticClassicalGuitars() {
            return base.Channel.GetAllAcousticClassicalGuitars();
        }
        
        public System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.AcousticClassicalGuitarDataModel[]> GetAllAcousticClassicalGuitarsAsync() {
            return base.Channel.GetAllAcousticClassicalGuitarsAsync();
        }
        
        public Legato.MiddlewareContracts.DataContracts.AcousticWesternGuitarDataModel[] GetAllAcousticWesternGuitars() {
            return base.Channel.GetAllAcousticWesternGuitars();
        }
        
        public System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.AcousticWesternGuitarDataModel[]> GetAllAcousticWesternGuitarsAsync() {
            return base.Channel.GetAllAcousticWesternGuitarsAsync();
        }
        
        public Legato.MiddlewareContracts.DataContracts.ElectroGuitarDataModel[] GetAllElectroGuitars() {
            return base.Channel.GetAllElectroGuitars();
        }
        
        public System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.ElectroGuitarDataModel[]> GetAllElectroGuitarsAsync() {
            return base.Channel.GetAllElectroGuitarsAsync();
        }
        
        public Legato.MiddlewareContracts.DataContracts.BassGuitarDataModel[] GetAllBassGuitars() {
            return base.Channel.GetAllBassGuitars();
        }
        
        public System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.BassGuitarDataModel[]> GetAllBassGuitarsAsync() {
            return base.Channel.GetAllBassGuitarsAsync();
        }
        
        public Legato.MiddlewareContracts.DataContracts.GuitarDataModel[] GetGuitarsByVendor(string vendor) {
            return base.Channel.GetGuitarsByVendor(vendor);
        }
        
        public System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.GuitarDataModel[]> GetGuitarsByVendorAsync(string vendor) {
            return base.Channel.GetGuitarsByVendorAsync(vendor);
        }
        
        public Legato.MiddlewareContracts.DataContracts.AcousticClassicalGuitarDataModel[] GetAcousticClassicalGuitarsByVendor(string vendor) {
            return base.Channel.GetAcousticClassicalGuitarsByVendor(vendor);
        }
        
        public System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.AcousticClassicalGuitarDataModel[]> GetAcousticClassicalGuitarsByVendorAsync(string vendor) {
            return base.Channel.GetAcousticClassicalGuitarsByVendorAsync(vendor);
        }
        
        public Legato.MiddlewareContracts.DataContracts.AcousticWesternGuitarDataModel[] GetAcousticWesternGuitarsByVendor(string vendor) {
            return base.Channel.GetAcousticWesternGuitarsByVendor(vendor);
        }
        
        public System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.AcousticWesternGuitarDataModel[]> GetAcousticWesternGuitarsByVendorAsync(string vendor) {
            return base.Channel.GetAcousticWesternGuitarsByVendorAsync(vendor);
        }
        
        public Legato.MiddlewareContracts.DataContracts.ElectroGuitarDataModel[] GetElectroGuitarsByVendor(string vendor) {
            return base.Channel.GetElectroGuitarsByVendor(vendor);
        }
        
        public System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.ElectroGuitarDataModel[]> GetElectroGuitarsByVendorAsync(string vendor) {
            return base.Channel.GetElectroGuitarsByVendorAsync(vendor);
        }
        
        public Legato.MiddlewareContracts.DataContracts.BassGuitarDataModel[] GetBassGuitarsByVendor(string vendor) {
            return base.Channel.GetBassGuitarsByVendor(vendor);
        }
        
        public System.Threading.Tasks.Task<Legato.MiddlewareContracts.DataContracts.BassGuitarDataModel[]> GetBassGuitarsByVendorAsync(string vendor) {
            return base.Channel.GetBassGuitarsByVendorAsync(vendor);
        }
    }
}
